#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 03, 2021 06:00:12 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
from main import *


def set_Tk_var():
    global choose
    choose = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def launch():
    try:
        cho = int(choose.get())
        if cho == 1:
            infinite_mode()
        elif cho == 2:
            time_mode()
    except ValueError:
        print("\n滚你妈，好好输！\n")

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import geosht
    geosht.vp_start_gui()




